
currentDir = pwd;

cd ../

cvx_paths = [
    [pwd '/cvx/builtins:'], ...
    [pwd '/cvx/commands:'], ...
    [pwd '/cvx/functions:'], ...
    [pwd '/cvx/lib:'], ...
    [pwd '/cvx/structures:'], ...
    [pwd '/cvx/functions/vec_:'], ...
    [pwd '/cvx:'], ...
    ];
 addpath(cvx_paths);
 
 cd(currentDir);